spring:
  application:
    name: VehicleRentalSystem-Backend
    version: 1.0.0.0

  datasource:
    url: jdbc:postgresql://localhost:5432/CarRentalSystem
    username: postgres
    password: sipl
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
